### PR TITLE
remove unneeded files

### PR DESCRIPTION
**Pull request by yannikschaelte**

### CODE REVIEW

**Review by mkroening — COMMENTED** [review]
Could `MiniInterface.dat` still be useful as example?
What is the reason not to remove the `install` directory entirely?

**Comment by yannikschaelte** [comment]
> Could `MiniInterface.dat` still be useful as example?

It is part still there in gh-pages branch. One could add a folder "examples" though for both this data, as well as the dummy miniplaner data set.

> What is the reason not to remove the `install` directory entirely?

Because 1) Still contains the old package build. That will maybe not be necessary anymore. 2) Contains example data for generating "pre-filled example miniplaners to try things out". If we create an "examples" folder, that would be superfluous.

**Comment by mkroening** [comment]
Ah, I see!

Are the examples from the `install` directory not the same as in the example zip on the website?

**Comment by yannikschaelte** [comment]
yes, they are. the example zip was actually built from the install folder. for new versions, I would like to keep this example mode, as having dummy data to play with has shown useful for many users.

**Comment by mkroening** [comment]
Ah, sorry! I was being misled by the commit message. I did not see, that you removed the unnecessary parts, which I was complaining about. Sorry!

LGTM!

**Review by mkroening — APPROVED** [review]

**Pull request merged**
